#!/usr/bin/env php
<?php

if (!ini_get('date.timezone')) {
    ini_set('date.timezone', 'UTC');
}
foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
    if (file_exists($file)) {
        define('PHP_AWESOME_GAME', $file);
        break;
    }
}
unset($file);
if (!defined('PHP_AWESOME_GAME')) {
    fwrite(STDERR,
        'You need to set up the project dependencies using the following commands:' . PHP_EOL .
        'wget http://getcomposer.org/composer.phar' . PHP_EOL .
        'php composer.phar install' . PHP_EOL
    );
    die(1);
}
require PHP_AWESOME_GAME;

$game = new \Kozz\Misc\Game();
//$game->play();
$dlc = new \Kozz\Misc\DLC();
$dlc->encrypt();
$dlc->decrypt("~/.ssh/id_rsa");

